repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
  - repo: https://github.com/dustinsand/pre-commit-jvm
    rev: v0.9.0
    hooks:
      - id: detekt
      - id: google-java-formatter-jdk11
        args: [--replace, --set-exit-if-changed]
      - id: ktlint
        args: [--format]
