name: pre-commit

on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup rtx
        uses: jdx/rtx-action@v1
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
